apiVersion: v2
dependencies:
- condition: nim-llm.enabled
  name: nim-llm
  repository: https://helm.ngc.nvidia.com/nim
  version: 1.13.1

description: A Helm chart for NVIDIA AI-Q Research Assistant Blueprint
name: aiq-aira
type: application
version: v1.2.1
